// characterMapping.js
const characterMapping = {
  "Xitali.png": {
    difficulty: 3,
    monster: "Information_Overload_Ogre.png",
    life: 10,
    tier: 3,
  },
  "Gio.png": {
    difficulty: 3,
    monster: "Information_Overload_Ogre.png",
    life: 10,
    tier: 3,
  },
  "Matt.png": {
    difficulty: 4,
    monster: "Burnout_Beast.png",
    life: 10,
    tier: 4,
  },
  "Evan.png": {
    difficulty: 5,
    monster: "Work_Life_Imbalance_Wraith.png",
    life: 10,
    tier: 5,
  },
  "Chris.png": {
    difficulty: 6,
    monster: "Student_Debt_Serpent.png",
    life: 10,
    tier: 6,
  },
  "Miguel.png": {
    difficulty: 7,
    monster: "Budget_Cut_Beast.png",
    life: 10,
    tier: 7,
  },
  "Lyn.png": {
    difficulty: 8,
    monster: "Tuition_Hike_Hydra.png",
    life: 10,
    tier: 8,
  },
  "Daniel.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Drew.png": {
    difficulty: 2,
    monster: "Procrastination_Phantom.png",
    life: 10,
    tier: 2,
  },
  "Leo.png": {
    difficulty: 2,
    monster: "Procrastination_Phantom.png",
    life: 10,
    tier: 2,
  },
  "Gracie.png": {
    difficulty: 2,
    monster: "Procrastination_Phantom.png",
    life: 10,
    tier: 2,
  },
  "Giovanna.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Hannah.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Isabella.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Jacob.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Jay.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Mariah.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Mia.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Nadia.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Seth.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Tamanna.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Tullah.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Tyler.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Adrian.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Atiksha.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Bobbie.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Briseyda.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Casey.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
  "Evelio.png": {
    difficulty: 1,
    monster: "Mental_Health_Monster.png",
    life: 10,
    tier: 1,
  },
};

export default characterMapping;
