const defeatWords = {
  "Procrastination_Phantom.png": [
    "Planning",
    "Responsibility",
    "Discipline",
    "Focus",
    "Time Management",
    "Motivation",
    "Goal Setting",
    "Prioritization",
    "Action",
    "Determination",
    "Efficiency",
    "Deadline",
    "Schedule",
    "Routine",
    "Commitment",
    "Proactivity",
    "Initiative",
    "Follow-through",
    "Consistency",
    "Self-Control",
    "Accountability",
  ],
  "Mental_Health_Monster.png": [
    "Support",
    "Therapy",
    "Exercise",
    "Meditation",
    "Sleep",
    "Healthy Eating",
    "Socializing",
    "Journaling",
    "Mindfulness",
    "Nature",
    "Relaxation",
    "Self-Care",
    "Boundaries",
    "Acceptance",
    "Compassion",
    "Positivity",
    "Resilience",
    "Routine",
    "Hydration",
    "Breathing",
    "Gratitude",
  ],
  "Information_Overload_Ogre.png": [
    "Organize",
    "Prioritize",
    "Breakdown",
    "Limit",
    "Focus",
    "Simplify",
    "Filter",
    "Delegate",
    "Batching",
    "Single-tasking",
    "Silence Notifications",
    "Schedule",
    "Declutter",
    "Categorize",
    "Routine",
    "Clear Goals",
    "Time Blocking",
    "Pause",
    "Minimalism",
    "Essentialism",
    "Decline",
  ],
  "Burnout_Beast.png": [
    "Rest",
    "Balance",
    "Break",
    "Delegation",
    "Boundaries",
    "Vacation",
    "Hobby",
    "Social Support",
    "Self-Care",
    "Mindfulness",
    "Sleep",
    "Healthy Eating",
    "Exercise",
    "Gratitude",
    "Meditation",
    "Positivity",
    "Relaxation",
    "Unplug",
    "Flexibility",
    "Joy",
    "Passion",
  ],
  "Work_Life_Imbalance_Wraith.png": [
    "Balance",
    "Time Off",
    "Hobby",
    "Family",
    "Rest",
    "Boundaries",
    "Exercise",
    "Relaxation",
    "Vacation",
    "Flexibility",
    "Socializing",
    "Self-Care",
    "Routine",
    "Prioritize",
    "Delegation",
    "Mindfulness",
    "Sleep",
    "Healthy Eating",
    "Joy",
    "Positivity",
    "Passion",
  ],
  "Student_Debt_Serpent.png": [
    "Scholarships",
    "Grants",
    "Savings",
    "Budgeting",
    "Jobs",
    "Work-Study",
    "Financial Aid",
    "Loans",
    "Cost Cutting",
    "Expense Tracking",
    "Side Hustle",
    "Internships",
    "Freelancing",
    "Grants",
    "Merit Aid",
    "Negotiation",
    "Stipends",
    "Crowdfunding",
    "Subsidies",
    "Emergency Fund",
    "Investment",
  ],
  "Budget_Cut_Beast.png": [
    "Efficiency",
    "Innovation",
    "Savings",
    "Fundraising",
    "Grants",
    "Cost Reduction",
    "Sponsorship",
    "Partnerships",
    "Revenue Streams",
    "Optimization",
    "Crowdfunding",
    "Donations",
    "Cost Sharing",
    "Streamlining",
    "Volunteerism",
    "Resource Allocation",
    "Outsourcing",
    "Shared Services",
    "Automation",
    "Lean Practices",
    "Grants",
  ],
  "Tuition_Hike_Hydra.png": [
    "Scholarships",
    "Financial Aid",
    "Work-Study",
    "Budgeting",
    "Savings",
    "Grants",
    "Loans",
    "Cost Cutting",
    "Expense Tracking",
    "Crowdfunding",
    "Part-time Job",
    "Internships",
    "Freelancing",
    "Negotiation",
    "Stipends",
    "Merit Aid",
    "Subsidies",
    "Investment",
    "Emergency Fund",
    "Savings Plans",
    "Employer Assistance",
  ],
};

export default defeatWords;